// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficAnalysisAPI.Data;

#nullable disable

namespace TrafficAnalysisAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421215818_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficAnalysisAPI.Models.FlowMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ACKFlagCount")
                        .HasColumnType("integer");

                    b.Property<int>("ActDataPktFwd")
                        .HasColumnType("integer");

                    b.Property<double>("ActiveMax")
                        .HasColumnType("double precision");

                    b.Property<double>("ActiveMean")
                        .HasColumnType("double precision");

                    b.Property<double>("ActiveMin")
                        .HasColumnType("double precision");

                    b.Property<double>("ActiveStd")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePacketSize")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgBwdSegmentSize")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgFwdSegmentSize")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdAvgBulkRate")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdAvgBytesBulk")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdAvgPacketsBulk")
                        .HasColumnType("double precision");

                    b.Property<int>("BwdHeaderLength")
                        .HasColumnType("integer");

                    b.Property<double>("BwdIATMax")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdIATMean")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdIATMin")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdIATStd")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdIATTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("BwdPSHFlags")
                        .HasColumnType("integer");

                    b.Property<double>("BwdPacketLengthMax")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdPacketLengthMean")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdPacketLengthMin")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdPacketLengthStd")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdPacketsPerSec")
                        .HasColumnType("double precision");

                    b.Property<int>("BwdURGFlags")
                        .HasColumnType("integer");

                    b.Property<int>("CWEFlagCount")
                        .HasColumnType("integer");

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("integer");

                    b.Property<double>("DownUpRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("ECEFlagCount")
                        .HasColumnType("integer");

                    b.Property<int>("FINFlagCount")
                        .HasColumnType("integer");

                    b.Property<double>("FlowBytesPerSec")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowDuration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FlowEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FlowIATMax")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowIATMean")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowIATMin")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowIATStd")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowPacketsPerSec")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FlowStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FwdAvgBulkRate")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdAvgBytesBulk")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdAvgPacketsBulk")
                        .HasColumnType("double precision");

                    b.Property<int>("FwdHeaderLength")
                        .HasColumnType("integer");

                    b.Property<double>("FwdIATMax")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdIATMean")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdIATMin")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdIATStd")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdIATTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("FwdPSHFlags")
                        .HasColumnType("integer");

                    b.Property<double>("FwdPacketLengthMax")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdPacketLengthMean")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdPacketLengthMin")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdPacketLengthStd")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdPacketsPerSec")
                        .HasColumnType("double precision");

                    b.Property<int>("FwdURGFlags")
                        .HasColumnType("integer");

                    b.Property<double>("IdleMax")
                        .HasColumnType("double precision");

                    b.Property<double>("IdleMean")
                        .HasColumnType("double precision");

                    b.Property<double>("IdleMin")
                        .HasColumnType("double precision");

                    b.Property<double>("IdleStd")
                        .HasColumnType("double precision");

                    b.Property<int>("InitWinBytesBackward")
                        .HasColumnType("integer");

                    b.Property<int>("InitWinBytesForward")
                        .HasColumnType("integer");

                    b.Property<int?>("Label")
                        .HasColumnType("integer");

                    b.Property<double>("MaxPacketLength")
                        .HasColumnType("double precision");

                    b.Property<double>("MinPacketLength")
                        .HasColumnType("double precision");

                    b.Property<int>("MinSegSizeForward")
                        .HasColumnType("integer");

                    b.Property<int>("PSHFlagCount")
                        .HasColumnType("integer");

                    b.Property<double>("PacketLengthMean")
                        .HasColumnType("double precision");

                    b.Property<double>("PacketLengthStd")
                        .HasColumnType("double precision");

                    b.Property<double>("PacketLengthVariance")
                        .HasColumnType("double precision");

                    b.Property<string>("PredictedBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("RSTFlagCount")
                        .HasColumnType("integer");

                    b.Property<int>("SYNFlagCount")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("SourcePort")
                        .HasColumnType("integer");

                    b.Property<long>("SubflowBwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowBwdPackets")
                        .HasColumnType("integer");

                    b.Property<long>("SubflowFwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowFwdPackets")
                        .HasColumnType("integer");

                    b.Property<string>("ThreatLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("ThreatScore")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalBackwardPackets")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFwdPackets")
                        .HasColumnType("integer");

                    b.Property<long>("TotalLengthBwdPackets")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalLengthFwdPackets")
                        .HasColumnType("bigint");

                    b.Property<int>("URGFlagCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Protocol");

                    b.HasIndex("SessionId");

                    b.HasIndex("ThreatLevel");

                    b.HasIndex("SourceIP", "DestinationIP");

                    b.ToTable("FlowMetrics");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.NetworkPacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("FlowId")
                        .HasColumnType("integer");

                    b.Property<int>("PacketSize")
                        .HasColumnType("integer");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationIP");

                    b.HasIndex("FlowId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SourceIP");

                    b.HasIndex("Timestamp");

                    b.ToTable("NetworkPackets");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.TrafficSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TrafficSessions");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$C83vSlJeLDe9HQKCTtAZauTtlT2s8sVbZtZIvGAmlrAR14wDDRkE.",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$uMJ6PYfgWhWPNFTshq.o1uukT0yYAuju3J6mVv1M32MXtrFhpnYB2",
                            Role = "Analyst",
                            Username = "analyst"
                        });
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.FlowMetrics", b =>
                {
                    b.HasOne("TrafficAnalysisAPI.Models.TrafficSession", "Session")
                        .WithMany("Flows")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.NetworkPacket", b =>
                {
                    b.HasOne("TrafficAnalysisAPI.Models.FlowMetrics", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrafficAnalysisAPI.Models.TrafficSession", "Session")
                        .WithMany("Packets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Flow");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.TrafficSession", b =>
                {
                    b.Navigation("Flows");

                    b.Navigation("Packets");
                });
#pragma warning restore 612, 618
        }
    }
}
