// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficAnalysisAPI.Data;

#nullable disable

namespace TrafficAnalysisAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417062303_AddFlowMetrics")]
    partial class AddFlowMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficAnalysisAPI.Models.FlowMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ACKFlagCount")
                        .HasColumnType("integer");

                    b.Property<int>("ActDataPktFwd")
                        .HasColumnType("integer");

                    b.Property<double>("ActiveMax")
                        .HasColumnType("double precision");

                    b.Property<double>("ActiveMean")
                        .HasColumnType("double precision");

                    b.Property<double>("ActiveMin")
                        .HasColumnType("double precision");

                    b.Property<double>("ActiveStd")
                        .HasColumnType("double precision");

                    b.Property<double>("AveragePacketSize")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgBwdSegmentSize")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgFwdSegmentSize")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdAvgBulkRate")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdAvgBytesBulk")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdAvgPacketsBulk")
                        .HasColumnType("double precision");

                    b.Property<int>("BwdHeaderLength")
                        .HasColumnType("integer");

                    b.Property<double>("BwdIATMax")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdIATMean")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdIATMin")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdIATStd")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdIATTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("BwdPSHFlags")
                        .HasColumnType("integer");

                    b.Property<double>("BwdPacketLengthMax")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdPacketLengthMean")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdPacketLengthMin")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdPacketLengthStd")
                        .HasColumnType("double precision");

                    b.Property<double>("BwdPacketsPerSec")
                        .HasColumnType("double precision");

                    b.Property<int>("BwdURGFlags")
                        .HasColumnType("integer");

                    b.Property<int>("CWEFlagCount")
                        .HasColumnType("integer");

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("integer");

                    b.Property<double>("DownUpRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("ECEFlagCount")
                        .HasColumnType("integer");

                    b.Property<int>("FINFlagCount")
                        .HasColumnType("integer");

                    b.Property<double>("FlowBytesPerSec")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowDuration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FlowEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FlowIATMax")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowIATMean")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowIATMin")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowIATStd")
                        .HasColumnType("double precision");

                    b.Property<double>("FlowPacketsPerSec")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FlowStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FwdAvgBulkRate")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdAvgBytesBulk")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdAvgPacketsBulk")
                        .HasColumnType("double precision");

                    b.Property<int>("FwdHeaderLength")
                        .HasColumnType("integer");

                    b.Property<double>("FwdIATMax")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdIATMean")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdIATMin")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdIATStd")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdIATTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("FwdPSHFlags")
                        .HasColumnType("integer");

                    b.Property<double>("FwdPacketLengthMax")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdPacketLengthMean")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdPacketLengthMin")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdPacketLengthStd")
                        .HasColumnType("double precision");

                    b.Property<double>("FwdPacketsPerSec")
                        .HasColumnType("double precision");

                    b.Property<int>("FwdURGFlags")
                        .HasColumnType("integer");

                    b.Property<double>("IdleMax")
                        .HasColumnType("double precision");

                    b.Property<double>("IdleMean")
                        .HasColumnType("double precision");

                    b.Property<double>("IdleMin")
                        .HasColumnType("double precision");

                    b.Property<double>("IdleStd")
                        .HasColumnType("double precision");

                    b.Property<int>("InitWinBytesBackward")
                        .HasColumnType("integer");

                    b.Property<int>("InitWinBytesForward")
                        .HasColumnType("integer");

                    b.Property<int?>("Label")
                        .HasColumnType("integer");

                    b.Property<double>("MaxPacketLength")
                        .HasColumnType("double precision");

                    b.Property<double>("MinPacketLength")
                        .HasColumnType("double precision");

                    b.Property<int>("MinSegSizeForward")
                        .HasColumnType("integer");

                    b.Property<int>("PSHFlagCount")
                        .HasColumnType("integer");

                    b.Property<double>("PacketLengthMean")
                        .HasColumnType("double precision");

                    b.Property<double>("PacketLengthStd")
                        .HasColumnType("double precision");

                    b.Property<double>("PacketLengthVariance")
                        .HasColumnType("double precision");

                    b.Property<string>("PredictedBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("RSTFlagCount")
                        .HasColumnType("integer");

                    b.Property<int>("SYNFlagCount")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("SourcePort")
                        .HasColumnType("integer");

                    b.Property<long>("SubflowBwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowBwdPackets")
                        .HasColumnType("integer");

                    b.Property<long>("SubflowFwdBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SubflowFwdPackets")
                        .HasColumnType("integer");

                    b.Property<string>("ThreatLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("ThreatScore")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalBackwardPackets")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFwdPackets")
                        .HasColumnType("integer");

                    b.Property<long>("TotalLengthBwdPackets")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalLengthFwdPackets")
                        .HasColumnType("bigint");

                    b.Property<int>("URGFlagCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Protocol");

                    b.HasIndex("SessionId");

                    b.HasIndex("SourceIP", "DestinationIP");

                    b.ToTable("FlowMetrics");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.NetworkPacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("PacketSize")
                        .HasColumnType("integer");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationIP");

                    b.HasIndex("SessionId");

                    b.HasIndex("SourceIP");

                    b.HasIndex("Timestamp");

                    b.ToTable("NetworkPackets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationIP = "10.0.0.1",
                            PacketSize = 500,
                            Port = 80,
                            Protocol = "TCP",
                            SessionId = 1,
                            SourceIP = "192.168.1.1",
                            Timestamp = new DateTime(2025, 10, 19, 12, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            DestinationIP = "10.0.0.2",
                            PacketSize = 2000,
                            Port = 23,
                            Protocol = "TCP",
                            SessionId = 1,
                            SourceIP = "45.142.120.15",
                            Timestamp = new DateTime(2025, 10, 19, 12, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            DestinationIP = "10.0.0.3",
                            PacketSize = 1800,
                            Port = 445,
                            Protocol = "TCP",
                            SessionId = 1,
                            SourceIP = "45.142.120.15",
                            Timestamp = new DateTime(2025, 10, 19, 12, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            DestinationIP = "10.0.0.4",
                            PacketSize = 1600,
                            Port = 3389,
                            Protocol = "TCP",
                            SessionId = 1,
                            SourceIP = "192.168.1.2",
                            Timestamp = new DateTime(2025, 10, 19, 12, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            DestinationIP = "10.0.0.5",
                            PacketSize = 600,
                            Port = 443,
                            Protocol = "HTTPS",
                            SessionId = 1,
                            SourceIP = "45.142.120.15",
                            Timestamp = new DateTime(2025, 10, 19, 12, 25, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.SourceMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AveragePacketSize")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<string>("ClusterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("DangerScore")
                        .HasColumnType("double precision");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("boolean");

                    b.Property<int>("PacketCount")
                        .HasColumnType("integer");

                    b.Property<double>("PacketsPerSecond")
                        .HasColumnType("double precision");

                    b.Property<string>("Protocols")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("UniquePorts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("IsDangerous");

                    b.HasIndex("SessionId");

                    b.HasIndex("SourceIP");

                    b.ToTable("SourceMetrics");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.TrafficAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMalicious")
                        .HasColumnType("boolean");

                    b.Property<double>("MLModelScore")
                        .HasColumnType("double precision");

                    b.Property<int>("PacketId")
                        .HasColumnType("integer");

                    b.Property<string>("ThreatLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PacketId")
                        .IsUnique();

                    b.HasIndex("ThreatLevel");

                    b.ToTable("TrafficAnalyses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DetectedAt = new DateTime(2025, 10, 19, 12, 10, 0, 0, DateTimeKind.Utc),
                            IsMalicious = true,
                            MLModelScore = 0.69999999999999996,
                            PacketId = 2,
                            ThreatLevel = "High"
                        },
                        new
                        {
                            Id = 2,
                            DetectedAt = new DateTime(2025, 10, 19, 12, 15, 0, 0, DateTimeKind.Utc),
                            IsMalicious = true,
                            MLModelScore = 0.84999999999999998,
                            PacketId = 3,
                            ThreatLevel = "Critical"
                        },
                        new
                        {
                            Id = 3,
                            DetectedAt = new DateTime(2025, 10, 19, 12, 20, 0, 0, DateTimeKind.Utc),
                            IsMalicious = false,
                            MLModelScore = 0.5,
                            PacketId = 4,
                            ThreatLevel = "Medium"
                        },
                        new
                        {
                            Id = 4,
                            DetectedAt = new DateTime(2025, 10, 19, 12, 25, 0, 0, DateTimeKind.Utc),
                            IsMalicious = false,
                            MLModelScore = 0.29999999999999999,
                            PacketId = 5,
                            ThreatLevel = "Low"
                        });
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.TrafficSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TrafficSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Тестовая сессия для демонстрации",
                            SessionName = "Test Session 2025-01-12",
                            StartTime = new DateTime(2025, 10, 19, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$C83vSlJeLDe9HQKCTtAZauTtlT2s8sVbZtZIvGAmlrAR14wDDRkE.",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$uMJ6PYfgWhWPNFTshq.o1uukT0yYAuju3J6mVv1M32MXtrFhpnYB2",
                            Role = "Analyst",
                            Username = "analyst"
                        });
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.FlowMetrics", b =>
                {
                    b.HasOne("TrafficAnalysisAPI.Models.TrafficSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.NetworkPacket", b =>
                {
                    b.HasOne("TrafficAnalysisAPI.Models.TrafficSession", "Session")
                        .WithMany("Packets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.SourceMetrics", b =>
                {
                    b.HasOne("TrafficAnalysisAPI.Models.TrafficSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.TrafficAnalysis", b =>
                {
                    b.HasOne("TrafficAnalysisAPI.Models.NetworkPacket", "Packet")
                        .WithOne("Analysis")
                        .HasForeignKey("TrafficAnalysisAPI.Models.TrafficAnalysis", "PacketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packet");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.NetworkPacket", b =>
                {
                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("TrafficAnalysisAPI.Models.TrafficSession", b =>
                {
                    b.Navigation("Packets");
                });
#pragma warning restore 612, 618
        }
    }
}
